[build]
  base = "."
  command = "npm ci && npm run build:netlify && ls -la dist && ls -la dist/certara-assignment && ls -la dist/certara-assignment/browser"
  publish = "dist/certara-assignment/browser"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200